[package]
name = "ydh"
version = "0.1.0"
authors = ["clintonboys <clintonboys@icloud.com>"]
edition = "2018"

[dependencies]
rltk = { version = "0.8.0" }
specs = "0.16.1"
specs-derive = "0.4.1"
serde= { version = "1.0.93", features = ["derive"] }
serde_json = "1.0.39"
counter = "0.4.3"